"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import { MovieCollection } from "./components/movie-collection";
import { NavigationBar } from "./components/navigation-bar";
import { MovieCollectionProvider } from "./context/MovieCollectionContext";
import { useState, useEffect } from "react";

const inter = Inter({ weight: "200", subsets: ["latin"] });

// export const metadata = {
//   title: "the movie plug",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="">
      <body className={`${inter.className} antialiased `}>
        <MovieCollectionProvider>
          {/* <MovieCollection /> */}
          {children}
        </MovieCollectionProvider>
      </body>
    </html>
  );
}
