import { Inter } from "next/font/google";
import "./globals.css";
import { MovieCollectionProvider } from "./contexts/MovieCollectionContext";
import { NavigationBar } from "./components/navigation-bar";
import { MovieCollection } from "./components/movie-collection";
const inter = Inter({ weight: "200", subsets: ["latin"] });

export const metadata = {
  title: "the movie plug",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="min-h-screen bg-background text-text-primary">
      <body className={`${inter.className} antialiased`}>
        <MovieCollectionProvider>
          <NavigationBar />
          {children}
          <MovieCollection />
        </MovieCollectionProvider>
      </body>
    </html>
  );
}
